/*
 * This file is generated by jOOQ.
*/
package com.eleTronics.jooq.domain;


import com.eleTronics.jooq.domain.tables.Comments;
import com.eleTronics.jooq.domain.tables.Posts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Elephants extends SchemaImpl {

    private static final long serialVersionUID = -89020315;

    /**
     * The reference instance of <code>elephants</code>
     */
    public static final Elephants ELEPHANTS = new Elephants();

    /**
     * The table <code>elephants.COMMENTS</code>.
     */
    public final Comments COMMENTS = com.eleTronics.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>elephants.POSTS</code>.
     */
    public final Posts POSTS = com.eleTronics.jooq.domain.tables.Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Elephants() {
        super("elephants", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comments.COMMENTS,
            Posts.POSTS);
    }
}
