/*
 * This file is generated by jOOQ.
*/
package com.eleTronics.jooq.domain;


import com.eleTronics.jooq.domain.tables.Comments;
import com.eleTronics.jooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in elephants
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>elephants.COMMENTS</code>.
     */
    public static final Comments COMMENTS = com.eleTronics.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>elephants.POSTS</code>.
     */
    public static final Posts POSTS = com.eleTronics.jooq.domain.tables.Posts.POSTS;
}
